### ISSUE TITLE
Error-Message is not displayed

### ISSUE THREAD

**Issue by KeyArts** [Horttcore/confirm-user-registration#1]
When a user that is not confirmed by the administrator, tries to login, an error box with an error message should appear. 
In my case only the the error box appears. :o( 
- I put a new error text in the settings tab. without any markup.
- There is no text even if i look into plain html. 

I'm using:
- Confirm User Registration: Version 2.1.1
- Wordpress: Version 3.6

Thanks for any help in advance.
KeyArts
![empty_error_message](https://f.cloud.github.com/assets/5398493/1094813/84f5d804-16d5-11e3-965d-f37d33a04956.PNG)

**Comment by Horttcore** [comment]
This is prolly because you are using a security plugin that removes any login errors.
